# https://howto.wared.fr/ubuntu-seedbox-docker-openvpn/#toggle-id-5
version: '3'
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:latest
    environment: 
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Paris
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359
      - 1900:1900
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./config/jellyfin:/config
      - downloads:/data
  deluge:
    image: ghcr.io/linuxserver/deluge:latest
    cap_add:
      - NET_ADMIN
    ports:
      - 8112:8112
      - 58846:58846
      - 58946:58946
      - 58946:58946/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DOCKER_MODS=ghcr.io/antoinefaul/mediabox/openvpn:main
    #network_mode: host
    volumes:
      - ./config/deluge:/config
      - downloads:/downloads
      - ./vpn.ovpn:/openvpn.conf
    devices:
      - /dev/net/tun 
  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    ports:
      - 9117:9117
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config/jackett:/config
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config/sonarr:/config
      - downloads:/data
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config/radarr:/config
      - downloads:/data
  lidarr:
    image: ghcr.io/linuxserver/lidarr:latest
    ports:
      - 8686:8686
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config/lidarr:/config
      - downloads:/data
  plex:
    image: ghcr.io/linuxserver/plex:latest
    ports:
      - 32400:32400
    environment:
      - VERSION=latest
      - PUID=1000
      - PGID=1000
      - TZ=Europe/paris
    volumes:
      - ./config/plex:/config
      - downloads:/data
  ombi:
    image: ghcr.io/linuxserver/ombi:latest
    ports:
      - 3579:3579
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/paris
    volumes:
      - ./config/ombi:/config
  traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/traefik.toml:ro
      - ./traefik/acme.json:/acme.json
volumes:
  downloads:
networks:
  default:
    #driver: bridge
