# https://howto.wared.fr/ubuntu-seedbox-docker-openvpn/#toggle-id-5
version: '3'
services:
  emby:
    # https://hub.docker.com/r/emby/embyserver
    image: linuxserver/emby:latest
    ports:
      - 8096:8096
      - 8920:8920
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/antoine/docker_perso/MediaBox/config/emby:/config
        #- film:/opt/movies
      - downloads:/data
  deluge:
    # https://hub.docker.com/r/linuxserver/deluge
    image: linuxserver/deluge:latest
    ports:
      - 8112:8112
      - 58846:58846
      - 58946:58946
      - 58946:58946/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    #network_mode: host
    volumes:
      - /home/antoine/docker_perso/MediaBox/config/deluge:/config
      - downloads:/downloads
# deluge:
#   # https://hub.docker.com/r/linuxserver/deluge
#   build: .
#   ports:
#     - 8112:8112
#     - 58846:58846
#     - 58946:58946
#     - 58946:58946/udp
#   environment:
#     - PUID=0
#     - PGID=0
#     - TZ=Europe/Paris
#   cap_add:
#     - NET_ADMIN
#     - SYS_ADMIN
#   devices:
#     - /dev/net/tun
#   #network_mode: host
#   volumes:
#     - /home/antoine/docker_perso/MediaBox/config/deluge:/config
#     - downloads:/downloads
#     - /home/antoine/docker_perso/MediaBox/nl-free-02.protonvpn.com.tcp.ovpn:/config.ovpn
#     - /home/antoine/docker_perso/MediaBox/ovpn.pass:/ovpn.pass
  jackett:
    image: linuxserver/jackett:latest
    ports:
      - 9117:9117
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/antoine/docker_perso/MediaBox/config/jackett:/config
  sonarr:
    image: linuxserver/sonarr:latest
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/antoine/docker_perso/MediaBox/config/sonarr:/config
      - downloads:/data
  radarr:
    image: linuxserver/radarr:latest
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/antoine/docker_perso/MediaBox/config/radarr:/config
      - downloads:/data
  lidarr:
    image: linuxserver/lidarr:latest
    ports:
      - 8686:8686
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/antoine/docker_perso/MediaBox/config/lidarr:/config
      - downloads:/data
  plex:
    image: linuxserver/plex:latest
    ports:
      - 32400:32400
    environment:
      - VERSION=latest
      - PUID=1000
      - PGID=1000
      - TZ=Europe/paris
    volumes:
      - /home/antoine/docker_perso/MediaBox/config/plex:/config
      - downloads:/data
  ombi:
    image: linuxserver/ombi:latest
    ports:
      - 3579:3579
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/paris
    volumes:
      - /home/antoine/docker_perso/MediaBox/config/ombi:/config
  traefik:
    image: traefik
    #ports:
      #- 80:80
      #- 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/antoine/docker_perso/MediaBox/config/traefik/traefik.toml:/traefik.toml:ro
      - /home/antoine/docker_perso/MediaBox/config/traefik/acme.json:/acme.json
volumes:
  downloads:
networks:
  default:
    driver: bridge
