apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-clusterissuer
  namespace: kube-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: antoine.faul@gmail.com
    privateKeySecretRef:
      name: letsencrypt-clusterissuer
    dns01: 
      providers:
        - name: aws-dns
          route53:
            region: eu-west-1
            accessKeyID: AWS_ACCESS_KEY_ID
            secretAccessKeySecretRef:
              name: aws-route53-creds
              key: password.txt
