apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seedbox-ingress
  annotations:
    cert-manager.io/issuer: letsencrypt-staging
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
#    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - emby.roon.fr
    secretName: emby-roon-tls
  rules:
  - host: emby.roon.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: emby
            port: 
              number: 8096
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api/letsencrypt.org/directory
    email: antoine.faul@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx

